<?php
$topic = $this->topic;
?>
<h2>Edit Topic</h2>
<form action="edit" method="POST">
    <label>
        Title: <input type="text" name="title" value="<?php $topic['title']; ?>">
    </label>
    <br>
    <label>
        Description:
        <br>
        <textarea name="description" cols="50" rows="20"><?php $topic['description']; ?></textarea>
    </label>
    <br>
    <input type="hidden" name="id" value="<?=$topic['id'];?>">
    <input type="submit" value="Edit Topic">
</form>